### ISSUE TITLE
Investigate/report upstream issue with exifreader on node 18

### ISSUE THREAD

**Issue by elstoc** [elstoc/home-api#18]
https://github.com/mattiasw/ExifReader

**Comment by elstoc** [comment]
Could possibly work around by fetching the file into a buffer first and delivering that to the exif reader.

**Comment by mattiasw** [comment]
Hi! Maintainer of ExifReader here. I stumbled upon this issue and I wanted to help. Please try version 4.7.0 that was just released and see if that helps with the issue you've had with Node 18.

**Comment by elstoc** [comment]
Wow way to be proactive, thanks!  It was an issue with fetch iirc but I didn't investigate much (I'm not in a desperate hurry to upgrade). I will investigate and get back to you.

**Comment by mattiasw** [comment]
Yeah, Node 18 added support for the Fetch API that browsers have and that had some consequences which made it go down the wrong execution path. I haven't tried all the variants of loading files but at least it doesn't throw that error anymore.

**Comment by elstoc** [comment]
It works. Thanks again!

**Comment by mattiasw** [comment]
Great to hear!
